### ISSUE TITLE
Need more configurable chain parameters

### ISSUE THREAD

**Issue by elric1** [tezedge/tezedge#655]
When starting tezedge, I see that you can specify `--network=foo` which selects a series of parameters such as the chain name, protocol, genesis block, etc. An example from the code of such a setting can be found in the code here:
```
    env.insert(TezosEnvironment::Sandbox, TezosEnvironmentConfiguration {
        genesis: GenesisChain {
            time: "2018-06-30T16:07:32Z".to_string(),
            block: "BLockGenesisGenesisGenesisGenesisGenesisf79b5d1CoW2".to_stri
ng(),
            protocol: "PtYuensgYBb3G3x1hLLbCmcav8ue8Kyd2khADcL5LsT5R1hcXex".to_s
tring(),
        },
        bootstrap_lookup_addresses: vec![],
        version: "SANDBOXED_TEZOS".to_string(),
        protocol_overrides: ProtocolOverrides {
            user_activated_upgrades: vec![],
            user_activated_protocol_overrides: vec![],
        },
        enable_testchain: false,
        patch_context_genesis_parameters: Some(PatchContext {
            key: "sandbox_parameter".to_string(),
            json: r#"{ "genesis_pubkey": "edpkuSLWfVU1Vq7Jg9FucPyKmma6otcMHac9zG
4oU1KMHSTBpJuGQ2" }"#.to_string(),
        }),
    });
```
For the tezos-k8s project, we need to be able to set some of these parameters arbitrarily. Here's the configuration section that we are using:
```
node_config_network:
  activation_account_name: baker0
  chain_name: SANDBOXED_TEZOS
  genesis:
    block: BLockGenesisGenesisGenesisGenesisGenesisf79b5d1CoW2
    protocol: PtYuensgYBb3G3x1hLLbCmcav8ue8Kyd2khADcL5LsT5R1hcXex
    timestamp: '2018-06-30T16:07:32Z'
```
We use the "activation account" to find the `genesis_pubkey` that ends up in the config file. But, as you can see, we need for various other fields from the above code block to be configurable.
